Fix save to be out of the lua loop
yetone/avante.nvim pull request #560
Opened 2024-09-10 09:10 UTC by leiserfg

2024-09-10 09:11 UTC, leiserfg commented
Fixes #559

2024-09-11 04:48 UTC, aarnphm commented on lua/avante/path.lua
> -M.save = function(bufnr, history)
I don't think this would fix the bug in #559, rather it might introduce more bugs.

`save` usually should be called synchronously.

2024-09-11 04:49 UTC, aarnphm requested changes
I think let's find the actual bug instead of this hack.

2024-09-11 05:37 UTC, leiserfg commented
The error comes from the fact that save calls history.get, which then calls vim.nvim_buf_get_name which needs to be scheduled.

2024-09-11 05:39 UTC, leiserfg commented
I'm not sure why delaying safe a few milliseconds will be a problem tho.

2024-09-13 08:19 UTC, leiserfg commented
Hi @aarnphm can you please help me with this?

2024-09-19 17:49 UTC, Lap1n commented
Looks like this proposed fix is the way it was suggested in this other closed issue on [plenary repo](https://github.com/nvim-lua/plenary.nvim/issues/189#issuecomment-882424314).

2024-09-20 03:23 UTC, yetone commented
This fix looks fine.

2024-10-08 02:46 UTC, ibanks42 commented
Can this get merged then? It's currently blocking me from using a local LLM.

2024-10-08 02:59 UTC, aarnphm approved these changes

2024-10-10 12:04 UTC, merged