fix(copilot): setup M.state when not initialized
yetone/avante.nvim pull request #862
Opened 2024-11-17 15:03 UTC by ethanh20009

fixes https://github.com/yetone/avante.nvim/issues/861

Copilot was broken and wouldn't work at all for me. PR resolves it.

2024-11-17 18:24 UTC, aarnphm requested changes
I don't think this fix it. let's investigate

2024-11-17 18:24 UTC, aarnphm commented on lua/avante/providers/copilot.lua
> +  if not M.state then M.setup() end
ugh this should be setup before hand, not to be called here.

2024-11-17 21:58 UTC, ethanh20009 commented on lua/avante/providers/copilot.lua
> +  if not M.state then M.setup() end
Found the root cause:
Copilot does not have an api_key_name as is setup in other plugin. 
In provider init, it checks for no api_key_name and early returns. In our case this is wrong as we need copilot setup.

So added a bool for providers that are set up without api keys.

2024-11-18 11:55 UTC, aarnphm commented
cc @yetone

2024-11-18 19:27 UTC, errnoh commented
Tested this with Copilot (gpt-4o-2024-08-06) and this fixes #861 for me. ( running avante https://github.com/yetone/avante.nvim/commit/9891b0365607373553b5dab74494a5e81b01e3c2 )

2024-11-18 21:14 UTC, yetone commented
‌‌‌‌Hello, I fixed this issue in this way because I really couldn't find a reason not to set up the provider: https://github.com/yetone/avante.nvim/pull/868

2024-11-18 21:14 UTC, closed without merging