fix(cmp): fix get_sources when blink.compat is installed
yetone/avante.nvim pull request #864
Opened 2024-11-17 17:06 UTC by rachartier

Hello,

`blink.cmp` has a module: `blink.compat`. This module is used to work with `nvim-cmp` sources but does not "emulate" all the functions present in `nvim-cmp`.

As a result, when the autocmds in the sidebar are set up and used (like quitting the sidebar), it is checked whether `require("cmp")` exists. With `blink.compat`, it does indeed exist, but the `get_sources` function used afterward does not, which causes an error: `Error executing lua callback: ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1547: attempt to call method 'get_sources' (a nil value)`

This small fix adds a check for the `get_sources` method. If it does not exist, the rest of the function is aborted.

2024-11-17 17:50 UTC, aarnphm commented on lua/avante/sidebar.lua
> +        if type(cmp.core.get_sources) == "function" then
Let's not do this. probably better to have cmp backend (we should add support to blink fwiw)

then update the callback here instead of doing this (otherwise maintenance cost are too high)

2024-11-17 17:50 UTC, aarnphm requested changes
tiny

2024-12-21 16:52 UTC, doodleEsc commented
tried with `blink.compat` and it works fine with first time.

`blink.cmp` call function is_available(), but  `self.bufnr` in `cmp_avante.commands` and `cmp_avante.mentions` will never change.

```lua
function commands_source:is_available() return api.nvim_get_current_buf() == self.bufnr end
```

I change `is_available` function
```
function commands_source:is_available() return vim.bo.filetype == "AvanteInput" end
```

#https://github.com/doodleEsc/avante.nvim/commit/a5438d0f16208b7ae9e97ae354bed5ec16b4f9ed


my LazyVim.nvim config, juse add `avante_commands` and `avante_mentions` in source.compat
```lua
  {

    "saghen/blink.cmp",
    opts = {
      sources = {
        compat = { "avante_commands", "avante_mentions" },
      },
    },
  },

```

it works for me

2025-02-27 04:02 UTC, yetone commented
‌Thank you for your contribution. Since this PR hasn't been updated for a long time, it has been closed. Sorry about that.

2025-02-27 04:02 UTC, closed without merging